#!/bin/sh
#
# Inicia o servidor REST systeminfo (porta 8080).
#

DAEMON="systeminfo"
PROG="/usr/bin/systeminfo"
PIDFILE="/var/run/$DAEMON.pid"
LOGFILE="/var/log/$DAEMON.log"

start() {
	printf "Starting %s: " "$DAEMON"
	start-stop-daemon -S -q -b -m -p "$PIDFILE" \
		-x /bin/sh -- -c "exec $PROG >> $LOGFILE 2>&1"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping %s: " "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	rm -f "$PIDFILE"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	sleep 1
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
